#!/bin/sh

# Install asn and it's init script.

[ "$ASN" = "" ] && ASN=asn-static
[ "$CHRDIR" = "" ] && CHRDIR=/var/chroot/asn

if [ -x $ASN ] ; then
	echo missing $ASN >/dev/stderr
	exit 2
fi

if [ -x $CHRDIR ] ; then
	echo missing $CHRDIR >/dev/stderr
	exit 2
fi

install -D $ASN $CHRDIR/usr/sbin/asn || exit $?
install -D start-stop-asn /etc/init.d/asn || exit $?
