#!/bin/sh

# Install asn and it's init script.

[ "$ASN" = "" ] && ASN=asn-static
[ "$CHRDIR" = "" ] && CHRDIR=/var/chroot/asn

for x in $ASN $CHRDIR; do
	if [ ! -x $x ] ; then
		echo missing $x >/dev/stderr
		exit 2
	fi
done

install -D $ASN $CHRDIR/usr/sbin/asn || exit $?
install -D start-stop-asn /etc/init.d/asn || exit $?
