#!/bin/sh

# Install asn and it's init script.

[ "$ASN" = "" ] && ASN=asn-static
[ "$CHRDIR" = "" ] && CHRDIR=/var/chroot/asn

if [ ! -x $ASN ] ; then
	echo missing $ASN >/dev/stderr
	exit 2
fi

if [ ! -x $CHRDIR ] ; then
	echo missing $CHRDIR >/dev/stderr
	exit 2
fi

if [ -x /etc/init.d/asn ] ; then
	/etc/init.d/asn stop
fi

install -D $ASN $CHRDIR/usr/sbin/asn || exit $?
install start-stop-asn /etc/init.d/asn || exit $?

for filter in find_friends; do
	test -x $filter && install $filter $CHRDIR/usr/sbin/$filter
done

/etc/init.d/asn start || exit $?
