#!/bin/bash

usage="${0##*/} thumb_NAME.svg full_NAME.svg"

: ${ASN_CONFIG:=test-adm}
: ${ASN_URL:=ws://104.154.68.215:80/asn/test-gcloud.ws}

if [[ $# -ne 2 ||
	${1%_*} != "thumb" ||
	${1##*.} != svg ||
	${2%_*} != "full" ||
	${2##*.} != svg ||
	${1#*thumb_} != ${2#*full_} ]]; then
	echo $usage >/dev/stderr
	exit 1
fi

upload-news() {
	newsA=${1##*/}
	newsB=${newsA/_//}
	newsC=${newsB//[[:space:]]/_}
	gzip -c $1 |
		./asn -config $ASN_CONFIG -server $ASN_URL blob /news/${newsC}.gz
}

upload-news $1
upload-news $2
