#!/bin/bash

usage="${0##*/} [-config CONFIG] thumb_NAME.svg full_NAME.svg"

: ${ASN_CONFIG:=test-adm}

if [[ "$1" =~ -*config=* ]] ; then
	ASN_CONFIG=${1#*=}
	shift 1
elif [[ "$1" =~ -*config ]] ; then
	ASN_CONFIG=$2
	shift 2
fi

thumb=${1##*/}
full=${2##*/}

if [[ $# -ne 2 ||
	${thumb%_*} != "thumb" ||
	${thumb##*.} != svg ||
	${full%_*} != "full" ||
	${full##*.} != svg ||
	${thumb#*thumb_} != ${full#*full_} ]]; then
	echo $usage >/dev/stderr
	exit 1
fi

upload_news() {
	newsA=${1##*/}
	newsB=${newsA/_//}
	newsC=${newsB//[[:space:]]/_}
	gzip -c $1 | ./asn -config $ASN_CONFIG blob /news/${newsC}.gz -
}

upload_news $1
upload_news $2
