#!/bin/bash

shopt -s extglob

if [[ "$1" =~ (-h|-help|--help|help) ]] ; then
	echo Usage: $0 '[-n|--dry-run] [-tags TAGS]'
	exit 0
fi

dryrun=
if [[ "$1" =~ (-n|--dry-run) ]] ; then
	dryrun=echo
	shift
fi

eval $dryrun go build -o docker/asn $@
eval $dryrun docker build -t asn docker
